server:
  port: '8080'
  
spring:
  profiles:
    active: ${ACTIVE_PROFILE}
  decryptKey: ${ENCRYPT_KEY}  
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(dVbhcuMT5bC8j2oUO7hKAQ==)
    url: jdbc:mysql://localhost:3306/dcbapp
    password: ENC(PNl6xCarOaK95gHebn5En8AgkTKISlc5)
  main:
    banner-mode: log
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: '"dev version 1.1"'
  
---  
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(dVbhcuMT5bC8j2oUO7hKAQ==)
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    password: ENC(PNl6xCarOaK95gHebn5En8AgkTKISlc5)
  main:
    banner-mode: log
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: '"qa version 1.1"' 
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans" 
  
---   
spring:
  config:
    activate:
      on-profile: aws
  h2:
    console:
      enabled: 'true'
  datasource:
    username: ENC(IN+E6mQ4kJEDr8hi6SjVCA==)
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    password: ENC(12aqE4nFZs7NauB3StFtDAB4mnTY1DVs)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
welcome:
  message: '"aws version 1.1"'  
  
---   
spring:
  config:
    activate:
      on-profile: awsrds
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${AWS_USERNAME}
    url: ${AWS_DB_URL}
    password: ${AWS_PASSWORD}
  main:
    banner-mode: log
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: ${WELCOME_MESSAGE}

